# Generated by Django 5.2.6 on 2025-09-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_reviewuser_testimonialuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.reviewuser'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.testimonialuser'),
        ),
        migrations.AlterField(
            model_name='testimonialuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
