# Generated by Django 5.2.6 on 2025-09-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_testimonial_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TestimonialUser',
        ),
    ]
