# Generated by Django 5.2.6 on 2025-09-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.profile'),
        ),
    ]
