# Generated by Django 5.2.6 on 2025-09-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
    ]
