# Generated by Django 5.2.6 on 2025-09-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_teacher_bio_teacher_email_teacher_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
